language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"
  - composer self-update

install:
  - composer update

script:
  - ./vendor/bin/phpunit;

jobs:
  include:
  - stage: Test
    name: Lowest dependencies
    php: 7.2
    install: composer update --prefer-dist --prefer-lowest

  - stage: Test
    name: Code coverage
    php: 7.2
    before_script:
    - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
    - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
    script:
    - ./vendor/bin/phpunit -v --coverage-clover ./build/logs/clover.xml
    after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover;

  - stage: Code Quality
    name: Static analysis
    php: 7.2
    install: composer require --dev phpstan/phpstan-shim ^0.10;
    script:
      - ./vendor/bin/phpstan analyse -l max -c phpstan.neon src tests --no-progress --no-interaction;

  - stage: Code Quality
    name: Coding standards
    php: 7.2
    install: composer require --dev friendsofphp/php-cs-fixer ^2.0;
    script:
      - ./vendor/bin/php-cs-fixer --dry-run -v fix;

  allow_failures:
  - php: nightly
=======
env:
  matrix:
    - DEPENDENCIES=""
    - DEPENDENCIES="--prefer-lowest --prefer-stable"
before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp; fi
  - if [[ $TRAVIS_PHP_VERSION != '7.3' ]]; then phpenv config-rm xdebug.ini ; fi
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION = '7.2' ]]; then composer require --dev phpstan/phpstan-shim ^0.10 friendsofphp/php-cs-fixer ^2.0; fi
install:
  - if [[ $TRAVIS_PHP_VERSION = '7.2' && DEPENDENCIES = '' ]]; then composer require --dev phpstan/phpstan-shim ^0.9 friendsofphp/php-cs-fixer ^2.13; fi
  - composer update $DEPENDENCIES
script:
  - ./vendor/bin/phpunit $COVERAGE;
  - if [[ $TRAVIS_PHP_VERSION = '7.2' && DEPENDENCIES = ''  ]]; then ./vendor/bin/php-cs-fixer --dry-run -v fix; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.2' && DEPENDENCIES = ''  ]]; then ./vendor/bin/phpstan analyse -l max -c phpstan.neon src tests --no-progress --no-interaction; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.2' && DEPENDENCIES = ''  ]]; then phpenv config-add /tmp/xdebug.ini; ./vendor/bin/phpunit --coverage-clover=coverage.clover; else ./vendor/bin/phpunit; fi
after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.2' && DEPENDENCIES = '' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
